package com.iss.app.Grade;
// default package
// Generated May 3, 2017 9:31:37 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblGrade generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "tbl_grade", schema = "iss_schema")
public class Grade implements java.io.Serializable {

	private long idgrade;
	private int number;
	private String name;

	public Grade() {
	}

	public Grade(long idgrade, int number, String name) {
		this.idgrade = idgrade;
		this.number = number;
		this.name = name;
	}

	@Id

	@Column(name = "idgrade", nullable = false)
	public long getIdgrade() {
		return this.idgrade;
	}

	public void setIdgrade(long idgrade) {
		this.idgrade = idgrade;
	}

	@Column(name = "number", nullable = false)
	public int getNumber() {
		return this.number;
	}

	public void setNumber(int number) {
		this.number = number;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
