package com.iss.app.Conference;
// default package
// Generated May 3, 2017 9:32:26 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.iss.app.User.User;

/**
 * TblConference generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "tbl_conference", schema = "iss_schema")
public class Conference implements java.io.Serializable {

	private int idconference;
	private Date deadline;
	private String type;
	private User user;

	public Conference() {
	}

	public Conference(int idconference, Date deadline, String type, User fkIduser) {
		this.idconference = idconference;
		this.deadline = deadline;
		this.type = type;
		this.user = fkIduser;
	}

	@Id

	@Column(name = "idconference", nullable = false)
	public int getIdconference() {
		return this.idconference;
	}

	public void setIdconference(int idconference) {
		this.idconference = idconference;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "deadline", nullable = false, length = 13)
	public Date getDeadline() {
		return this.deadline;
	}

	public void setDeadline(Date deadline) {
		this.deadline = deadline;
	}

	@Column(name = "type", nullable = false, length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}
	
	@ManyToOne(targetEntity=User.class)
	@JoinColumn(name="fk_iduser")
	public User getUser() {
		return this.user;
	}

	public void setUser(User fkIduser) {
		this.user = fkIduser;
	}

}
