package com.iss.app.Proposal;
// default package
// Generated May 3, 2017 9:29:50 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.iss.app.User.User;

/**
 * TblProposal generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "tbl_proposal", schema = "iss_schema")
public class Proposal implements java.io.Serializable {

	private int idproposal;
	private User user;
	private User userReviewer;
	private String name;
	private byte[] document;
	private String domain;
	private Integer averagemark;

	public Proposal() {
	}

	
	

	@Id

	@Column(name = "idproposal", nullable = false)
	public int getIdproposal() {
		return this.idproposal;
	}

	public void setIdproposal(int idproposal) {
		this.idproposal = idproposal;
	}

	
	@ManyToOne(targetEntity=User.class)
	@JoinColumn(name="fk_iduser")
	public User getUser() {
		return this.user;
	}

	public void setUser(User fkIduser) {
		this.user = fkIduser;
	}
	@ManyToOne(targetEntity=User.class)
	@JoinColumn(name="fk_iduser_reviewer")
	public User getUserReviewer() {
		return this.userReviewer;
	}

	public void setUserReviewer(User fkIduserReviewer) {
		this.userReviewer = fkIduserReviewer;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "document")
	public byte[] getDocument() {
		return this.document;
	}

	public void setDocument(byte[] document) {
		this.document = document;
	}

	@Column(name = "domain", nullable = false, length = 50)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "averagemark")
	public Integer getAveragemark() {
		return this.averagemark;
	}

	public void setAveragemark(Integer averagemark) {
		this.averagemark = averagemark;
	}

}
