package com.iss.app.AccessLevel;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblAccessLevel generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "tbl_access_level", schema = "iss_schema")
public class AccessLevel implements java.io.Serializable {

	private long idlevel;
	private String levelName;

	public AccessLevel() {
	}

	public AccessLevel(long idlevel, String levelName) {
		this.idlevel = idlevel;
		this.levelName = levelName;
	}

	@Id

	@Column(name = "idlevel", nullable = false)
	public long getIdlevel() {
		return this.idlevel;
	}

	public void setIdlevel(long idlevel) {
		this.idlevel = idlevel;
	}

	@Column(name = "level_name", nullable = false, length = 50)
	public String getLevelName() {
		return this.levelName;
	}

	public void setLevelName(String levelName) {
		this.levelName = levelName;
	}

}
