package com.iss.app.User;
// default package
// Generated May 3, 2017 9:28:55 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.iss.app.AccessLevel.AccessLevel;

/**
 * TblUser generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "tbl_user", schema = "iss_schema")
public class User implements java.io.Serializable {

	private long iduser;
	private String email;
	private String name;
	private AccessLevel accessLevel;
	private String username;
	private String password;
	private String maddress;
	private String address;
	private byte[] photo;
	private String nationality;
	private String mobile;

	public User() {
	}

	public User(long iduser, String email, String name, AccessLevel fkIdlevel,String address,String maddress,String nationality,String mobile,byte[] photo) {
		this.iduser = iduser;
		this.email = email;
		this.name = name;
		this.accessLevel = fkIdlevel;
		this.address = address;
		this.maddress = maddress;
		this.nationality = nationality;
		this.mobile = mobile;
		this.photo=photo;
	}

	@Id

	@Column(name = "iduser", nullable = false)
	public long getIduser() {
		return this.iduser;
	}

	public void setIduser(long iduser) {
		this.iduser = iduser;
	}

	@Column(name = "email", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	@ManyToOne(targetEntity=AccessLevel.class)
	@JoinColumn(name="fk_idlevel")
	public AccessLevel getAccessLevel() {
		return this.accessLevel;
	}

	public void setAccessLevel(AccessLevel fkIdlevel) {
		this.accessLevel = fkIdlevel;
	}
	
	@Column(name = "username", length = 30)
	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}
	@Column(name = "password", nullable = false, length = 30)
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	@Column(name = "maddress", nullable = false, length = 50)
	public String getMaddress() {
		return maddress;
	}

	public void setMaddress(String maddress) {
		this.maddress = maddress;
	}
	@Column(name = "address", nullable = false, length = 50)
	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}
	
	@Column(name = "photo", nullable = true)
	public byte[] getPhoto() {
		return photo;
	}
	
	public void setPhoto(byte[] photo) {
		this.photo = photo;
	}
	@Column(name = "nationality", nullable = false, length = 50)
	public String getNationality() {
		return nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}
	@Column(name = "mobile", nullable = false, length = 50)
	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}
	

}
